name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]
  schedule:
    - cron: "0 9-16 * * 1-5"

jobs:
  bot:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.5

      - name: Get Stock Price
        run: |
          curl -o ticker.sh https://raw.githubusercontent.com/pstadler/ticker.sh/master/ticker.sh
          chmod +x ticker.sh
          export PRICE=$(NO_COLOR=1 ./ticker.sh TSLA 2>&1 | awk -F" " '{print $2}')
          echo "PRICE=$PRICE" >> $GITHUB_ENV

      - name: Tweet Stock Price
        uses: Eomm/why-don-t-you-tweet@v1
        if: github.repository == 'jaredsburrows/botteslastock' && github.ref == 'refs/heads/main'
        with:
          tweet-message: "$TLSA ${{ env.PRICE }}"
        env:
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

#      - name: Tweet Stock Price
#        uses: snow-actions/tweet@v1.2.0
#        with:
#          status: "$TLSA ${{ env.PRICE }}"
#        env:
#          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
#          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
#          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
#          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
